services:
  # El Orquestador / Proxy Inverso (Único expuesto al puerto 80)
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend-despacho
      - backend-ventas
    networks:
      - red-monorepo

  # FRONTEND (React / Vite - Configuración limpia de producción)
  frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
      args:
        VITE_API_DESPACHOS: http://localhost/api/v1/despachos
        VITE_API_VENTAS: http://localhost/api/v1/ventas
    container_name: front-despacho  # ← mismo nivel que build
    networks:
      - red-monorepo

  # BASE DE DATOS (MySQL 8.0)
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: dbevaluacion
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: devops_password
      MYSQL_ROOT_PASSWORD: root_password_seguro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "devops_user", "-pdevops_password"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - red-monorepo

  # BACKEND DESPACHOS (Spring Boot en 8081)
  backend-despacho:
    build:
      context: ./back-Despachos_SpringBoot/SpringBoot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: back-despacho
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=dbevaluacion
      - DB_USERNAME=devops_user
      - DB_PASSWORD=devops_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red-monorepo

  # BACKEND VENTAS (Spring Boot en 8082)
  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: back-ventas
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=dbevaluacion
      - DB_USERNAME=devops_user
      - DB_PASSWORD=devops_password
    depends_on:
      db:
        condition: service_healthy
        
    networks:
      - red-monorepo
networks:
  red-monorepo:
    driver: bridge