services:
  # El Orquestador / Proxy Inverso (Único expuesto al puerto 80)
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - red-monorepo

  # FRONTEND (React / Vite)
  frontend:
    image: ghcr.io/debugggmax/frontend-despacho-v2:latest
    container_name: front-despacho
    networks:
      - red-monorepo

  # BASE DE DATOS (MySQL 8.0)
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: dbevaluacion
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: devops_password
      MYSQL_ROOT_PASSWORD: root_password_seguro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "devops_user", "-pdevops_password"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red-monorepo

  # BACKEND DESPACHOS (Spring Boot en 8081)
  backend-despacho:
    image: ghcr.io/debugggmax/backend-despacho:latest
    container_name: back-despacho
    environment:
      - DB_ENDPOINT=10.0.4.48
      - DB_PORT=3306
      - DB_NAME=dbevaluacion
      - DB_USERNAME=devops_user
      - DB_PASSWORD=devops_password
    networks:
      - red-monorepo

  # BACKEND VENTAS (Spring Boot en 8082)
  backend-ventas:
    image: ghcr.io/debugggmax/backend-ventas:latest
    container_name: back-ventas
    environment:
      - DB_ENDPOINT=10.0.4.48
      - DB_PORT=3306
      - DB_NAME=dbevaluacion
      - DB_USERNAME=devops_user
      - DB_PASSWORD=devops_password
    networks:
      - red-monorepo

volumes:
  mysql_data:

networks:
  red-monorepo:
    driver: bridge